---
# Task: Fetch sosreport diagnostics

- name: Fetch sosreport archive md5
  fetch: >
    src={{ tmpdir }}/{{ diag_filename }}.md5
    dest=/tmp/jsos/{{ ansible_hostname }}/
    fail_on_missing=yes
    flat=yes
    validate_md5=yes

- name: Fetch sosreport archives
  fetch: >
    src={{ tmpdir }}/{{ diag_filename }}
    dest={{ diag_path }}/{{ ansible_hostname }}/
    flat=yes
    validate_md5=no
